[functions]
  external_node_modules = ["express", "mongoose", "morgan", "cors", "dotenv", "serverless-http"]
  node_bundler = "esbuild"

[build]
  command = "echo \"no build\"" 
  publish = "."            

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true